// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8KQjYIdlDiFcv3ptXXN8mfxxrMyuRlVA',
    appId: '1:343091285389:web:1a0ad3503342bb56ac41c4',
    messagingSenderId: '343091285389',
    projectId: 'fooddeliveryapp-7d5e0',
    authDomain: 'fooddeliveryapp-7d5e0.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-7d5e0.appspot.com',
    measurementId: 'G-0CHJJ2BL9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLD6duw1zL5u35J7iXeKNiFzEITXlQhQk',
    appId: '1:343091285389:android:5fe59101bc22a3b7ac41c4',
    messagingSenderId: '343091285389',
    projectId: 'fooddeliveryapp-7d5e0',
    storageBucket: 'fooddeliveryapp-7d5e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxZlyUoEbzAgsoJ4J8Gaoadv5k8biiUI',
    appId: '1:343091285389:ios:14f14a378b66f7c0ac41c4',
    messagingSenderId: '343091285389',
    projectId: 'fooddeliveryapp-7d5e0',
    storageBucket: 'fooddeliveryapp-7d5e0.appspot.com',
    iosClientId: '343091285389-4bh4vcbbcsk4h89b2tfiaselufs2i1hh.apps.googleusercontent.com',
    iosBundleId: 'com.food.delivery.foodDeliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNxZlyUoEbzAgsoJ4J8Gaoadv5k8biiUI',
    appId: '1:343091285389:ios:14f14a378b66f7c0ac41c4',
    messagingSenderId: '343091285389',
    projectId: 'fooddeliveryapp-7d5e0',
    storageBucket: 'fooddeliveryapp-7d5e0.appspot.com',
    iosClientId: '343091285389-4bh4vcbbcsk4h89b2tfiaselufs2i1hh.apps.googleusercontent.com',
    iosBundleId: 'com.food.delivery.foodDeliveryApp',
  );
}
